apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-demo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh","-c","while true; do echo 'Ephemeral Data' >> /data/file.txt; sleep 5; done"]
    volumeMounts:
    - name: temp-storage
      mountPath: /data

  volumes:
  - name: temp-storage
    emptyDir: {}
