apiVersion: v1
kind: Pod
metadata:
  name: dynamic-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh","-c","while true; do echo 'Persistent Data' >> /data/file.txt; sleep 5; done"]
    volumeMounts:
    - mountPath: /data
      name: storage

  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: local-dynamic-pvc

